import { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { db, getSettings, saveReadingPosition } from '../services/database';
import { offsetDistance } from '../services/logic';
import type { DisplayMode, NotationMode, Setlist, Song } from '../types/models';
import { PdfView } from './PdfView';
import { GuitarProView } from './GuitarProView';

export function Reader() {
  const { id } = useParams(); const navigate = useNavigate(); const [searchParams] = useSearchParams(); const [song, setSong] = useState<Song>(); const [setlist, setSetlist] = useState<Setlist>(); const [pages, setPages] = useState(1); const [menu, setMenu] = useState(true); const [documentTheme, setDocumentTheme] = useState('white'); const [offsetStep, setOffsetStep] = useState(50); const [tracks, setTracks] = useState<{ index: number; name: string; program: number }[]>([]); const container = useRef<HTMLDivElement>(null); const pointer = useRef<{ x: number; y: number; multi: boolean } | undefined>(undefined);
  useEffect(() => { void (async () => { const loaded = id ? await db.songs.get(id) : undefined; if (!loaded) { navigate('/'); return; } const listId = searchParams.get('setlist'); setSetlist(listId ? await db.setlists.get(listId) : undefined); const settings = await getSettings(); setDocumentTheme(settings.documentTheme); setOffsetStep(settings.offsetStep); const updated = { ...loaded, lastOpenedAt: Date.now() }; await db.songs.put(updated); setSong(updated); try { await navigator.wakeLock?.request('screen'); } catch { /* optional browser feature */ } })(); }, [id, navigate, searchParams]);
  const update = (changes: Partial<Song>) => { if (!song) return; const next = { ...song, ...changes }; setSong(next); void saveReadingPosition(next.id, next); };
  const go = (direction: -1 | 1) => { if (!song) return; const motion = matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth'; if (song.fileType === 'guitar-pro') { const percentage = song.displayMode === 'offset' ? offsetStep : song.displayMode === 'page' ? 100 : 75; container.current?.scrollBy({ top: direction * offsetDistance(innerHeight, percentage), behavior: motion }); return; } if (song.displayMode === 'continuous') { container.current?.scrollBy({ top: direction * offsetDistance(innerHeight, 75), behavior: motion }); return; } if (song.displayMode === 'offset') { container.current?.scrollBy({ top: direction * offsetDistance(innerHeight, offsetStep), behavior: motion }); return; } update({ currentPage: Math.max(1, Math.min(pages, song.currentPage + direction)) }); };
  useEffect(() => { const keyboard = (event: KeyboardEvent) => { if (event.key === 'Escape') menu ? setMenu(false) : navigate('/'); if (['ArrowRight', 'PageDown', ' '].includes(event.key)) { event.preventDefault(); go(1); } if (['ArrowLeft', 'PageUp'].includes(event.key)) { event.preventDefault(); go(-1); } }; addEventListener('keydown', keyboard); return () => removeEventListener('keydown', keyboard); });
  if (!song) return <main className="reader-loading">Partitur wird geöffnet ...</main>;
  const setlistIndex = setlist && song ? setlist.orderedSongIds.indexOf(song.id) : -1;
  const openSetlistSong = (direction: -1 | 1) => { if (!setlist || setlistIndex < 0) return; const nextId = setlist.orderedSongIds[setlistIndex + direction]; if (nextId) navigate(`/reader/${nextId}?setlist=${setlist.id}`); };
  const onPointerUp = (event: React.PointerEvent) => { const start = pointer.current; if (!start || start.multi || Math.hypot(event.clientX - start.x, event.clientY - start.y) > 12 || menu) return; const fraction = event.clientX / innerWidth; if (fraction < .3) go(-1); else if (fraction > .7) go(1); else setMenu(true); };
  return <main className="reader" ref={container} onScroll={() => song.displayMode === 'continuous' && update({ scrollPosition: container.current?.scrollTop ?? 0 })} onPointerDown={event => { pointer.current = { x: event.clientX, y: event.clientY, multi: event.isPrimary === false }; }} onPointerUp={onPointerUp}>
    {menu && <header className="reader-menu"><button onClick={() => navigate('/')}>Bibliothek</button><button aria-label="Zurückblättern" onClick={() => go(-1)}>Zurück</button><button aria-label="Weiterblättern" onClick={() => go(1)}>Weiter</button>{setlist && <><button disabled={setlistIndex <= 0} onClick={() => openSetlistSong(-1)}>Vorheriger Song</button><span>{setlistIndex + 1} von {setlist.orderedSongIds.length}</span><button disabled={setlistIndex >= setlist.orderedSongIds.length - 1} onClick={() => openSetlistSong(1)}>Nächster Song</button></>}<strong>{song.title}</strong><label>Modus <select value={song.displayMode} onChange={event => update({ displayMode: event.target.value as DisplayMode })}><option value="page">Seite</option><option value="offset">Halbe Seite</option><option value="continuous">Endlos</option></select></label><label>Zoom <input type="range" min="0.5" max="2" step="0.1" value={song.zoomLevel} onChange={event => update({ zoomLevel: Number(event.target.value) })} /></label>{song.fileType === 'guitar-pro' && <><label>Notation <select value={song.notationMode} onChange={event => update({ notationMode: event.target.value as NotationMode })}><option value="both">Beides</option><option value="standard">Notation</option><option value="tabs">Tabulatur</option></select></label><label>Spuren <select multiple value={song.selectedTrackIds.map(String)} onChange={event => update({ selectedTrackIds: Array.from(event.target.selectedOptions, option => Number(option.value)) })}>{tracks.map(track => <option key={track.index} value={track.index}>{track.name}</option>)}</select></label></>}<button onClick={() => update({ zoomLevel: 1 })}>Zurücksetzen</button></header>}
    {song.fileType === 'pdf' ? <PdfView file={song.fileBlob} page={song.currentPage} zoom={song.zoomLevel} mode={song.displayMode} documentTheme={documentTheme} onPages={setPages} /> : <GuitarProView file={song.fileBlob} zoom={song.zoomLevel} selectedTrackIds={song.selectedTrackIds} notationMode={song.notationMode} onTracks={setTracks} />}
  </main>;
}
