import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { db, defaultSettings, findSongByOriginalFileName, getSettings, storageEstimate } from './services/database';
import { createBackup, validateBackup } from './services/backup';
import { titleFromFileName, validateFile } from './services/files';
import { downloadBlob, sortSongs, type SortOrder } from './services/logic';
import type { Setlist, Settings, Song } from './types/models';

const ids = () => crypto.randomUUID();
const size = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(bytes < 1048576 ? 2 : 1)} MB`;
export function App() {
  const [songs, setSongs] = useState<Song[]>([]); const [setlists, setSetlists] = useState<Setlist[]>([]); const [settings, setSettings] = useState<Settings>(defaultSettings); const [query, setQuery] = useState(''); const [sort, setSort] = useState<SortOrder>('title'); const [filter, setFilter] = useState<'all' | 'favorite'>('all'); const [notice, setNotice] = useState(''); const fileInput = useRef<HTMLInputElement>(null); const backupInput = useRef<HTMLInputElement>(null);
  const refresh = async () => { setSongs(await db.songs.toArray()); setSetlists(await db.setlists.toArray()); setSettings(await getSettings()); };
  useEffect(() => { void refresh(); }, []);
  useEffect(() => { document.documentElement.dataset.theme = settings.appTheme; }, [settings.appTheme]);
  const importFiles = async (files: FileList | File[]) => { setNotice('Dateien werden importiert ...'); let imported = 0; for (const file of Array.from(files)) { try { const info = await validateFile(file); const existing = await findSongByOriginalFileName(file.name); if (existing) { const action = prompt(`„${file.name}“ existiert bereits. Eingabe: e = ersetzen, n = erneut importieren, a = abbrechen`, 'a'); if (action === 'a' || action === null) continue; if (action === 'e') await db.songs.delete(existing.id); if (!['e', 'n'].includes(action)) continue; } await db.songs.put({ id: ids(), title: titleFromFileName(file.name), originalFileName: file.name, fileType: info.type, mimeType: info.mimeType, fileBlob: file, fileSize: file.size, importedAt: Date.now(), lastOpenedAt: null, isFavorite: false, currentPage: 1, scrollPosition: 0, zoomLevel: 1, displayMode: 'page', selectedTrackIds: [], notationMode: 'both' }); imported++; } catch (error) { console.error(error); setNotice(error instanceof Error ? error.message : 'Die Datei konnte nicht importiert werden.'); } } await refresh(); if (imported) setNotice(`${imported} Datei(en) lokal importiert.`); };
  const updateSettings = async (changes: Partial<Settings>) => { const next = { ...settings, ...changes }; await db.settings.put(next); setSettings(next); };
  const makeSetlist = async () => { const title = prompt('Name der neuen Setliste'); if (!title?.trim()) return; await db.setlists.put({ id: ids(), title: title.trim(), createdAt: Date.now(), updatedAt: Date.now(), orderedSongIds: [] }); await refresh(); };
  const addToSetlist = async (songId: string) => { if (!setlists.length) { setNotice('Bitte zuerst eine Setliste anlegen.'); return; } const selected = prompt(`Setliste wählen:\n${setlists.map((list, index) => `${index + 1}: ${list.title}`).join('\n')}`); const list = setlists[Number(selected) - 1]; if (!list || list.orderedSongIds.includes(songId)) return; await db.setlists.put({ ...list, orderedSongIds: [...list.orderedSongIds, songId], updatedAt: Date.now() }); await refresh(); };
  const exportBackup = async () => { downloadBlob(new Blob([JSON.stringify(createBackup(await db.songs.toArray(), await db.setlists.toArray(), settings), null, 2)], { type: 'application/json' }), 'stage-reader-backup.json'); };
  const importBackup = async (file: File) => { try { const backup = validateBackup(JSON.parse(await file.text())); const conflict = backup.songs.some(song => songs.some(current => current.id === song.id)); if (conflict && !confirm('Bestehende Metadaten mit derselben ID werden ersetzt. Fortfahren?')) return; await db.transaction('rw', db.setlists, db.settings, async () => { await db.setlists.bulkPut(backup.setlists); await db.settings.put(backup.settings); }); await refresh(); setNotice('Backup-Metadaten importiert. Originaldateien bleiben aus Datenschutzgründen auf diesem Gerät.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Backup konnte nicht importiert werden.'); } };
  const shown = sortSongs(songs.filter(song => (filter === 'all' || song.isFavorite) && song.title.toLowerCase().includes(query.toLowerCase())), sort);
  return <main className="app-shell" onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); void importFiles(event.dataTransfer.files); }}>
    <header className="app-header"><div><p className="eyebrow">OFFLINE NOTENBIBLIOTHEK</p><h1>Stage Reader</h1></div><button className="primary" onClick={() => fileInput.current?.click()}>Datei hinzufügen</button><input ref={fileInput} hidden type="file" multiple accept=".pdf,.gp,.gp3,.gp4,.gp5,.gpx,application/pdf" onChange={event => event.target.files && void importFiles(event.target.files)} /></header>
    <section className="toolbar" aria-label="Bibliothek filtern"><input aria-label="Songs suchen" placeholder="Songs durchsuchen" value={query} onChange={event => setQuery(event.target.value)} /><button className={filter === 'all' ? 'selected' : ''} onClick={() => setFilter('all')}>Alle ({songs.length})</button><button className={filter === 'favorite' ? 'selected' : ''} onClick={() => setFilter('favorite')}>Favoriten</button><select aria-label="Sortierung" value={sort} onChange={event => setSort(event.target.value as SortOrder)}><option value="title">Titel</option><option value="opened">Zuletzt geöffnet</option><option value="imported">Zuletzt importiert</option><option value="type">Dateityp</option></select></section>
    {notice && <p className="notice" role="status">{notice}</p>}
    <section className="library" aria-label="Songbibliothek">{shown.length ? shown.map(song => <article className="song" key={song.id}><div><span className="file-type">{song.fileType === 'pdf' ? 'PDF' : 'Guitar Pro'}</span><h2>{song.title}</h2><p>{song.lastOpenedAt ? `Zuletzt geöffnet: ${new Date(song.lastOpenedAt).toLocaleDateString('de-DE')}` : 'Noch nicht geöffnet'} · {size(song.fileSize)}</p></div><div className="song-actions"><Link className="primary" to={`/reader/${song.id}`}>Öffnen</Link><button aria-label="Favorit umschalten" onClick={() => { void db.songs.update(song.id, { isFavorite: !song.isFavorite }).then(refresh); }}>{song.isFavorite ? '★' : '☆'}</button><button onClick={() => { const title = prompt('Songtitel', song.title); if (title?.trim()) void db.songs.update(song.id, { title: title.trim() }).then(refresh); }}>Umbenennen</button><button onClick={() => void addToSetlist(song.id)}>Zu Setliste</button><button onClick={() => downloadBlob(song.fileBlob, song.originalFileName)}>Download</button><button className="danger" onClick={() => confirm(`„${song.title}“ wirklich löschen?`) && void db.songs.delete(song.id).then(refresh)}>Löschen</button></div></article>) : <div className="empty"><h2>Deine Bibliothek ist leer</h2><p>Füge PDF- oder Guitar-Pro-Dateien hinzu. Sie bleiben nur auf diesem Gerät.</p></div>}</section>
    <section className="setlists"><div className="section-title"><h2>Setlisten</h2><button onClick={() => void makeSetlist()}>Setliste erstellen</button></div>{setlists.map(list => <article className="setlist" key={list.id}><strong>{list.title}</strong><span>{list.orderedSongIds.length} Songs</span>{list.orderedSongIds.length > 0 && <Link className="primary" to={`/reader/${list.orderedSongIds[0]}?setlist=${list.id}`}>Starten</Link>}<button className="danger" onClick={() => confirm(`Setliste „${list.title}“ löschen?`) && void db.setlists.delete(list.id).then(refresh)}>Löschen</button></article>)}</section>
    <section className="settings"><h2>Einstellungen</h2><p>Alle Dateien und Einstellungen werden ausschließlich lokal auf diesem Gerät gespeichert.</p><label>App-Theme <select value={settings.appTheme} onChange={event => void updateSettings({ appTheme: event.target.value as Settings['appTheme'] })}><option value="dark">Dunkel</option><option value="light">Hell</option><option value="system">System</option></select></label><label>Dokumentdarstellung <select value={settings.documentTheme} onChange={event => void updateSettings({ documentTheme: event.target.value as Settings['documentTheme'] })}><option value="white">Weiß</option><option value="warm">Warmweiß</option><option value="dark">Dunkel</option></select></label><label>Halbseiten-Schritt <select value={settings.offsetStep} onChange={event => void updateSettings({ offsetStep: Number(event.target.value) as Settings['offsetStep'] })}>{[40, 50, 60, 75, 100].map(value => <option key={value} value={value}>{value}%</option>)}</select></label><div><button onClick={() => void storageEstimate().then(estimate => setNotice(`${songs.length} Songs gespeichert, ungefähr ${size(estimate.usage ?? 0)} belegt.`))}>Speicher anzeigen</button><button onClick={() => void exportBackup()}>Metadaten exportieren</button><button onClick={() => backupInput.current?.click()}>Backup importieren</button><input ref={backupInput} hidden type="file" accept="application/json,.json" onChange={event => event.target.files?.[0] && void importBackup(event.target.files[0])} /><button onClick={() => void navigator.storage?.persist?.().then(result => setNotice(result ? 'Dauerhafter Speicher wurde angefragt.' : 'Dauerhafter Speicher ist nicht verfügbar.'))}>Speicher schützen</button><button className="danger" onClick={() => confirm('Wirklich alle lokalen Dateien, Setlisten und Einstellungen löschen?') && void db.delete().then(() => location.reload())}>Alle lokalen Daten löschen</button></div></section>
  </main>;
}
